# Generated by Django 3.0.8 on 2020-07-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200714_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
    ]
