# Generated by Django 3.0.8 on 2020-07-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_starters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Starters',
            new_name='MenuList',
        ),
    ]
