# Generated by Django 3.0.8 on 2020-07-16 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200715_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('Liked', models.BooleanField()),
                ('Msg_text', models.CharField(max_length=4000)),
                ('User_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='Created_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menus',
            name='Created_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
